modLoader="javafml"
loaderVersion="[1,)"
license="Apache-2.0"

[[mods]]
modId="evilkaraoke"
version="${version}"
displayName="Evilkaraoke"
description='''Evilkaraoke server commands and client audio playback for server-authoritative karaoke sessions.'''
authors="Evil-Project"

[[dependencies.evilkaraoke]]
modId="neoforge"
type="required"
versionRange="[26.2,)"
ordering="NONE"
side="BOTH"

[[dependencies.evilkaraoke]]
modId="minecraft"
type="required"
versionRange="[26.2,26.3)"
ordering="NONE"
side="BOTH"
